Jonatan Baumgartner Massimo De Santis Florian Feuillade

# Exercice 2 - System evaluation

## Imports

In [159]:
import pandas as pd
import numpy as np

## Load data

Define the path of the data file

In [160]:
path = "ex2-system-a.csv"

Read the CSV file using `read_csv`

In [161]:
dataset_a = pd.read_csv(path, sep=";", index_col=False, names=["0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "y_true"])

Display first rows

In [162]:
dataset_a.head()

0             1             2             3             4  \
0  5.348450e-08  7.493480e-10  8.083470e-07  2.082290e-05  5.222360e-10   
1  1.334270e-03  3.202960e-05  8.504280e-01  1.669090e-03  1.546460e-07   
2  3.643050e-06  9.962760e-01  2.045910e-03  4.210530e-04  2.194020e-05   
3  9.998200e-01  2.550390e-10  1.112010e-05  1.653200e-05  5.375730e-10   
4  2.092460e-08  7.464220e-08  3.560820e-05  5.496200e-07  9.988960e-01   

              5             6             7             8         9  y_true  
0  2.330260e-08  5.241270e-12  9.999650e-01  4.808590e-07  0.000013       7  
1  2.412940e-04  1.448280e-01  1.122810e-11  1.456330e-03  0.000011       2  
2  1.644130e-05  2.838160e-04  3.722960e-04  5.150120e-04  0.000044       1  
3  8.999750e-05  9.380920e-06  4.464470e-05  2.418440e-06  0.000006       0  
4  3.070920e-08  2.346150e-04  9.748010e-07  1.071610e-06  0.000831       4

Store some useful statistics (class names + number of classes)

In [163]:
class_names = ["0", "1", "2", "3", "4", "5", "6", "7", "8", "9"]
nb_classes = len(class_names)

## Exercise's steps

a) Write a function to take classification decisions on such outputs according to Bayes’rule.

In [164]:
def bayes_classification(df):
    """
    Take classification decisions according to Bayes rule.
        
    Parameters
    ----------
    df : Pandas DataFrame of shape (n_samples, n_features + ground truth)
         Dataset.
         
    Returns
    -------
    preds : Numpy array of shape (n_samples,)
            Class labels for each data sample.
    """
    # Your code here
    ground_true = df["y_true"]
    df_no_y = df.drop("y_true", axis=1)

    maxValueIndexObj = df_no_y.idxmax(axis=1)
    return maxValueIndexObj.astype(int).to_numpy()

In [165]:
bayes_pred = bayes_classification(dataset_a)

b) What is the overall error rate of the system ?

In [166]:
# Your code here: compute and print the error rate of the system
def error_rate(df, bayes_pred):
    return (df["y_true"].to_numpy() != bayes_pred).sum() / bayes_pred.size

error_rate(dataset_a, bayes_pred)

0.1073

c) Compute and report the confusion matrix of the system.

In [167]:
def confusion_matrix(y_true, y_pred, n_classes):
    """
    Compute the confusion matrix.
        
    Parameters
    ----------
    y_true : Numpy array of shape (n_samples,)
             Ground truth.
    y_pred : Numpy array of shape (n_samples,)
             Predictions.
    n_classes : Integer
                Number of classes.
         
    Returns
    -------
    cm : Numpy array of shape (n_classes, n_classes)
         Confusion matrix.
    """
    # Your code here
    conf_mat = np.array([[0 for x in range(nb_classes)] for x in range(nb_classes)])
    for i in range(len(y_true)) :
        conf_mat[y_true[i]][y_pred[i]] = conf_mat[y_true[i]][y_pred[i]] + 1
    return conf_mat

In [168]:
# Your code here: compute and print the confusion matrix
cm = confusion_matrix(dataset_a["y_true"].to_numpy(), bayes_pred, 10)
cm

array([[ 944,    0,   11,    0,    0,    2,   10,    7,    5,    1],
       [   0, 1112,    2,    3,    1,    4,    3,    1,    9,    0],
       [  10,    6,  921,   12,   15,    3,   19,   15,   26,    5],
       [   1,    1,   31,  862,    2,   72,    5,   14,   12,   10],
       [   2,    3,    6,    2,  910,    1,   12,    6,    4,   36],
       [  12,    3,    6,   29,   19,  768,   19,    9,   21,    6],
       [  14,    3,   21,    2,   22,   28,  865,    0,    3,    0],
       [   0,   14,   30,    9,    7,    2,    1,  929,    3,   33],
       [  12,   16,   18,   26,   24,   46,   22,   19,  772,   19],
       [  10,    4,    6,   22,   53,   18,    0,   48,    4,  844]])

d) What are the worst and best classes in terms of precision and recall ?

In [169]:
def precision_per_class(cm):
    """
    Compute the precision per class.
        
    Parameters
    ----------
    cm : Numpy array of shape (n_classes, n_classes)
         Confusion matrix.
         
    Returns
    -------
    precisions : Numpy array of shape (n_classes,)
                 Precision per class.
    """
    # Your code here
    col = np.apply_along_axis(lambda x: x/x.sum(), 0, cm).diagonal()
    return col
ppc = precision_per_class(cm)
ppc

array([0.93930348, 0.95697074, 0.87547529, 0.89141675, 0.86419753,
       0.81355932, 0.90481172, 0.88645038, 0.89871944, 0.88469602])

In [170]:
def recall_per_class(cm):
    """
    Compute the recall per class.
        
    Parameters
    ----------
    cm : Numpy array of shape (n_classes, n_classes)
         Confusion matrix.
         
    Returns
    -------
    recalls : Numpy array of shape (n_classes,)
              Recall per class.
    """
    # Your code here
    line = np.apply_along_axis(lambda x: x/x.sum(), 1, cm).diagonal()
    return line
rpc = recall_per_class(cm)
rpc

array([0.96326531, 0.97973568, 0.89244186, 0.85346535, 0.92668024,
       0.86098655, 0.90292276, 0.9036965 , 0.7926078 , 0.83647175])

In [171]:
# Your code here: find and print the worst and best classes in terms of precision
print(f"The best class in terms of precision is : {ppc.argmax()}")
print(f"The worst class in terms of precision is : {ppc.argmin()}")

The best class in terms of precision is : 1
The worst class in terms of precision is : 5


In [172]:
# Your code here: find and print the worst and best classes in terms of recall
print(f"The best class in terms of recall is : {rpc.argmax()}")
print(f"The worst class in terms of recall is : {rpc.argmin()}")

The best class in terms of recall is : 1
The worst class in terms of recall is : 8


e) In file `ex1-system-b.csv` you find the output of a second system B. What is the best system between (a) and (b) in terms of error rate and F1.

In [173]:
# Your code here: load the data of the system B
path = "ex2-system-b.csv"
dataset_b = pd.read_csv(path, sep=";", index_col=False, names=["0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "y_true"])

In [174]:
def system_accuracy(cm):
    """
    Compute the system accuracy.
        
    Parameters
    ----------
    cm : Numpy array of shape (n_classes, n_classes)
         Confusion matrix.
         
    Returns
    -------
    accuracy : Float
               Accuracy of the system.
    """
    return cm.diagonal().sum() / cm.sum()

In [175]:
def system_f1_score(cm):
    """
    Compute the system F1 score.
        
    Parameters
    ----------
    cm : Numpy array of shape (n_classes, n_classes)
         Confusion matrix.
         
    Returns
    -------
    f1_score : Float
               F1 score of the system.
    """
    # Your code here
    precision = precision_per_class(cm)
    recall = recall_per_class(cm)
    return np.mean(2*(precision*recall/(precision+recall)))

In [176]:
# Your code here: compute and print the accuracy and the F1 score of the system A
y_pred = bayes_classification(dataset_a)
cm = confusion_matrix(dataset_a["y_true"].to_numpy(), y_pred, 10)
print(f"Accuracy : {system_accuracy(cm)}")
print(f"F1-Score : {system_f1_score(cm)}")

Accuracy : 0.8927
F1-Score : 0.8907308492877297


In [177]:
# Your code here: compute and print the accuracy and the F1 score of the system B
y_pred = bayes_classification(dataset_b)
cm = confusion_matrix(dataset_b["y_true"].to_numpy(), y_pred, 10)
print(f"Accuracy : {system_accuracy(cm)}")
print(f"F1-Score : {system_f1_score(cm)}")

Accuracy : 0.9613
F1-Score : 0.9608568150389065
